// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function() {
    var domain, handler, http;
    http = require('http');
    domain = require('domain');
    handler = function(request, response, next) {
      var errorNext, findNearErrorLayer, findNearNormalLayer, findParentNext, index, normalNext, parent, responseWith;
      findParentNext = function() {
        var pIndex, pNext;
        pIndex = parent.stack.indexOf(handler);
        return pNext = parent.stack[pIndex + 1];
      };
      responseWith = function(code) {
        response.statusCode = code;
        return response.end();
      };
      if (handler.stack.length === 0) {
        if (parent = handler.parent) {
          findParentNext()(request, response);
        } else {
          responseWith(404);
          return;
        }
      }
      index = -1;
      findNearNormalLayer = function(index) {
        var s, _i, _len, _ref;
        _ref = handler.stack.slice(index);
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          s = _ref[_i];
          if (s.length < 4) {
            return s;
          }
        }
      };
      findNearErrorLayer = function(index) {
        var s, _i, _len, _ref;
        _ref = handler.stack.slice(index);
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          s = _ref[_i];
          if (s.length === 4) {
            return s;
          }
        }
      };
      errorNext = function(err) {
        var nextLayer;
        if (nextLayer = findNearErrorLayer(index)) {
          return nextLayer(err, request, response, next);
        } else {
          if (parent = handler.parent) {
            return findParentNext()(err, request, response);
          } else {
            return responseWith(500);
          }
        }
      };
      normalNext = function() {
        var e, nextLayer;
        if (nextLayer = findNearNormalLayer(index)) {
          try {
            return nextLayer(request, response, next);
          } catch (_error) {
            e = _error;
            return responseWith(500);
          }
        } else {
          return responseWith(404);
        }
      };
      next = function(err) {
        index += 1;
        if (err) {
          return errorNext(err);
        } else {
          return normalNext();
        }
      };
      return next();
    };
    handler.listen = function(port, callback) {
      return http.createServer(handler).listen(port, callback);
    };
    handler.stack = [];
    handler.use = function(middleware) {
      if (middleware.stack) {
        middleware.parent = handler;
      }
      return handler.stack.push(middleware);
    };
    return handler;
  };

}).call(this);
