// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function() {
    var domain, handler, http;
    http = require('http');
    domain = require('domain');
    handler = function(request, response) {
      var errorNext, findNearErrorStack, findNearNormalStack, index, next, normalNext, responseWith;
      if (handler.stack.length === 0) {
        response.statusCode = 404;
        response.end();
        return;
      }
      index = -1;
      findNearNormalStack = function(index) {
        var s, _i, _len, _ref;
        _ref = handler.stack.slice(index);
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          s = _ref[_i];
          if (s.length < 4) {
            return s;
          }
        }
      };
      findNearErrorStack = function(index) {
        var s, _i, _len, _ref;
        _ref = handler.stack.slice(index);
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          s = _ref[_i];
          if (s.length === 4) {
            return s;
          }
        }
      };
      responseWith = function(code) {
        response.statusCode = code;
        return response.end();
      };
      errorNext = function(err) {
        var nextStack;
        if (nextStack = findNearErrorStack(index)) {
          return nextStack(err, request, response, next);
        } else {
          return responseWith(500);
        }
      };
      normalNext = function() {
        var e, nextStack;
        if (nextStack = findNearNormalStack(index)) {
          try {
            return nextStack(request, response, next);
          } catch (_error) {
            e = _error;
            return responseWith(500);
          }
        } else {
          return responseWith(404);
        }
      };
      next = function(err) {
        index += 1;
        if (err) {
          return errorNext(err);
        } else {
          return normalNext();
        }
      };
      return next();
    };
    handler.listen = function(port, callback) {
      return http.createServer(handler).listen(port, callback);
    };
    handler.stack = [];
    handler.use = function(middleware) {
      return handler.stack.push(middleware);
    };
    return handler;
  };

}).call(this);
