// Generated by CoffeeScript 1.7.1
(function() {
  var Layer;

  Layer = (function() {
    function Layer(path, handle) {
      this.path = path;
      this.handle = handle;
    }

    Layer.prototype.match = function(path) {
      if (path.indexOf(this.path) >= 0) {
        return {
          path: this.path
        };
      }
    };

    return Layer;

  })();

  module.exports = Layer;

}).call(this);
